# Default pre-commit hooks for coding projects
# TODO:
# - Add additional language formatters
#   - Rust
#   - Scala
#   - OCaml?
#   - Zig?

default_stages: [commit] # Needed to avoid duplicate installs on multiple stages
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
    - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.3
    hooks:
    - id: clang-format

  # TODO: Update this to apply on the commit-msg hook, not
  #       prepare-commit-msg
  - repo: https://github.com/njdup/devmoji-precommit
    rev: v1.3.0
    hooks:
    - id: devmoji-precommit

