.PHONY: dev
dev: ## Run in development mode
	npm run dev

.PHONY: build
build: ## Build for "production"
	npm run build

.PHONY: help
help: ## Show this help
	@grep -E '^[a-z.A-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
