# Default pre-commit hooks for coding projects
# TODO:
# - Add scala, clorjue hooks
# - Add rust hooks?

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.3
    hooks:
    - id: clang-format

