# Get editor completions based on the config schema
"$schema"   = 'https://starship.rs/config-schema.json'

format      = """$conda$username$directory$git_branch$git_status
[](bold red)[](bold purple)[](bold yellow) """

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) in '
disabled = false
show_always = true

[conda]
format = '\[$symbol$environment\] '
ignore_base = false

