[default]
zsh = "latest"
atuin = "latest"
fd = "latest"
starship = "latest"
tmux = "latest"
vlc = "latest"
terraform = "latest"
python-pre-commit = "latest"
fzf = "latest"
ranger = "latest"
python-pygments = "latest"
git-delta = "latest"
httpie = "latest"
htop = "latest"
glow = "latest"
cloc = "latest"
timew = "latest"
sqlite = "latest"
man-db = "latest"
shellcheck = "latest"
github-cli = "latest"
lazygit = "latest"
helix = "latest"
zig = "latest"
yt-dlp = "latest"
python-pipx = "latest"
pandoc-cli = "latest"

[yay]
ascii-image-converter = "latest"
gleam = "latest"
lazydocker = "latest"
slides = "latest"

[cargo]
bat = "latest"
coreutils = "latest"
du-dust = "latest"
exa = "latest"
ncspot = "latest"
porsmo = "latest"
ripgrep = "latest"
bottom = "latest"
wthrr = "latest"
cargo-update = "latest"
stylua = "latest"
mprocs = "latest"

[pip]
yewtube = "latest"
termdown = "latest"
wakatime = "latest"
pgcli = "latest"
onsen = "latest"
smassh = "latest"
harlequin = "latest"
gdtoolkit = "4.*"

[pipx]
posting = "latest"

[go]
github.com/maaslalani/nap = "main"
github.com/guyfedwards/nom/cmd/nom = "latest"
mvdan.cc/sh/v3/cmd/shfmt = "latest"

[npm]
@withgraphite/graphite-cli = "stable"
