-- Colorscheme generated by https://github.com/arcticlimer/djanho
-- TODO: remove some of these settings to keep the tokyo-night
--       settings:
--       - yellow line numbers
--       - bright red error underlines
--       - white indentation guides
--       - status column add/remove/change colors
--       - cursor line highlight
--       - gutter error messages
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color10 = '#19736d'
local Color5 = '#6FC1FF'
local Color9 = '#1a1b26'
local Color12 = '#534237'
local Color13 = '#232433'
local Color11 = '#752e4a'
local Color2 = '#E6E6E6'
local Color1 = '#FF75B5'
local Color3 = '#FFB86C'
local Color0 = '#676B79'
local Color4 = '#19f9d8'
local Color7 = '#dec5ff'
local Color8 = '#a9b1d6'
local Color6 = '#B084EB'

highlight('Comment', nil, Color0, 'italic')
highlight('Keyword', nil, Color1, nil)
highlight('Operator', nil, Color2, nil)
highlight('Type', nil, Color3, nil)
highlight('Constant', nil, Color3, nil)
highlight('Identifier', nil, Color2, nil)
highlight('String', nil, Color4, nil)
highlight('Function', nil, Color5, nil)
highlight('Type', nil, Color4, 'italic')
highlight('StatusLine', Color7, Color6, nil)
highlight('WildMenu', Color9, Color8, nil)
highlight('Pmenu', Color9, Color8, nil)
highlight('PmenuSel', Color8, Color9, nil)
highlight('PmenuThumb', Color9, Color8, nil)
highlight('DiffAdd', Color10, nil, nil)
highlight('DiffDelete', Color11, nil, nil)
highlight('Normal', Color9, Color8, nil)
highlight('Visual', Color12, nil, nil)
highlight('CursorLine', Color12, nil, nil)
highlight('ColorColumn', Color12, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('TabLine', Color13, Color7, nil)
highlight('TabLineSel', Color4, Color9, nil)
highlight('TabLineFill', Color13, Color7, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSProperty', 'TSField')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Conditional', 'Operator')
link('TSFunction', 'Function')
link('TSParameter', 'Constant')
link('TSConstant', 'Constant')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSPunctBracket', 'MyTag')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('TSTagDelimiter', 'Type')
link('TSComment', 'Comment')
link('Operator', 'Keyword')
link('TSOperator', 'Operator')
link('TSNamespace', 'TSType')
link('CursorLineNr', 'Identifier')
link('TSField', 'Constant')
link('TSLabel', 'Type')
link('TSFloat', 'Number')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TSTag', 'MyTag')
link('TSString', 'String')
link('Whitespace', 'Comment')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('TSNumber', 'Number')
link('TSKeyword', 'Keyword')
link('Macro', 'Function')
