# Default pre-commit hooks for coding projects
#
# These should be confined to operations that transform, manipulate,
# or otherwise interact with the commit process; code manipulations
# like linting or formatting are better enforced in a code editor,
# a makefile, and/or CI workflow

default_stages: [commit] # Needed to avoid duplicate installs on multiple stages
repos:
  # TODO: Update this to apply on the commit-msg hook, not
  #       prepare-commit-msg
  - repo: https://github.com/dupe-codes/devmoji-precommit
    rev: v1.3.0
    hooks:
    - id: devmoji-precommit
